bobMinimumVersion: "1.2.0"

# Keep ssh-agent working.
layersWhitelist: ["SSH_AGENT_PID", "SSH_AUTH_SOCK"]

layers:
  - name: basement
    scm: git
    url: https://github.com/codelabs-ch/basement.git
    commit: 9a5af22e8ca555f06e90730c27646322d8a5e509
    branch: rh-misc

  - name: basement-gnu-linux
    scm: git
    url: https://github.com/codelabs-ch/basement-gnu-linux.git
    commit: 9f9484594836723181b342625d4d800abf215f16
    branch: rh-misc

  - name: ada
    scm: git
    url: https://git.codelabs.ch/bob/ada.git
    #    branch: main
    commit: 7bdbffd867352b8dfdb87dcac897f3c15af93adb

  - name: codelabs
    scm: git
    url: https://git.codelabs.ch/bob/codelabs.git
    #    branch: main
    commit: a41bfc089b2d48eb56cb5549c32ba6ac04f0106e

layersInclude:
  - override_layers
