#!/usr/bin/env python3
"""Generate fixtures.h from device-tree sources compiled by an external dtc.

The committed fixtures.h is the output of this script. `make fixtures-check
DTC=/path/to/dtc` regenerates it and compares, so each valid fixture is
independently produced by dtc rather than hand-assembled.
"""
import argparse
import os
import struct
import subprocess
import tempfile


def nested(depth):
    """A root node plus (depth - 1) nested children (total nesting depth)."""
    body = ""
    for i in range(depth - 1):
        body += "n%d { " % i
    body += "};" * (depth - 1)
    return "/dts-v1/;\n/ { %s };\n" % body


FIXTURES = [
    ("fdt_min", "/dts-v1/;\n/ { };\n", ["-V", "17"]),
    ("fdt_v16", "/dts-v1/;\n/ { };\n", ["-V", "16"]),
    (
        "fdt_model",
        '/dts-v1/;\n/memreserve/ 0x80000000 0x10000;\n'
        '/ {\n\tmodel = "NVIDIA \\"test\\" board";\n'
        '\t#address-cells = <2>;\n\tcpus { model = "not-root"; };\n};\n',
        ["-V", "17"],
    ),
    ("fdt_model_64", '/dts-v1/;\n/ { model = "%s"; };\n' % ("M" * 64), ["-V", "17"]),
    (
        "fdt_model_long",
        '/dts-v1/;\n/ { model = "%s"; };\n' % ("L" * 64 + "-overflow-" + "T" * 26),
        ["-V", "17"],
    ),
    ("fdt_model_escape", '/dts-v1/;\n/ { model = "tab\\there\\\\back"; };\n', ["-V", "17"]),
    ("fdt_model_nonascii", '/dts-v1/;\n/ { model = "na\\xc3\\xafve"; };\n', ["-V", "17"]),
    ("fdt_model_list", '/dts-v1/;\n/ { model = "a", "b"; };\n', ["-V", "17"]),
    ("fdt_depth_64", nested(64), ["-V", "17"]),
    ("fdt_depth_65", nested(65), ["-V", "17"]),
]


def emit(lines, name, data):
    lines.append("static const uint8_t %s[%d] = {" % (name, len(data)))
    for i in range(0, len(data), 12):
        lines.append("    " + ",".join("0x%02x" % b for b in data[i : i + 12]) + ",")
    lines.append("};")


def with_leading_nop(data):
    """Insert one FDT_NOP before the root node of a dtc-produced v17 blob."""
    words = list(struct.unpack(">10I", data[:40]))
    total, off_struct, off_strings, off_rsv = words[1], words[2], words[3], words[4]
    assert off_rsv < off_struct < off_strings and words[9] + off_struct <= off_strings
    words[1] = total + 4
    words[3] = off_strings + 4
    words[9] += 4
    body = data[40:off_struct] + struct.pack(">I", 4) + data[off_struct:]
    return struct.pack(">10I", *words) + body


def check_same_tree(dtc, tmp, original, derived):
    """fdtdump (same dtc release) must show the same tree plus one NOP.

    The DT specification says FDT_NOP tokens are ignored by any parser;
    dtc 1.6.1's own blob reader nevertheless insists on FDT_BEGIN_NODE as
    the first token, so fdtdump is used for this derived fixture.
    """
    fdtdump = os.path.join(os.path.dirname(dtc), "fdtdump")
    ignored = ("// totalsize:", "// off_dt_strings:", "// size_dt_struct:", "// [NOP]")
    outputs = []
    for index, blob in enumerate((original, derived)):
        path = os.path.join(tmp, "check%d.dtb" % index)
        with open(path, "wb") as handle:
            handle.write(blob)
        dump = subprocess.run(
            [fdtdump, path], check=True, capture_output=True, text=True
        ).stdout.splitlines()
        outputs.append([line for line in dump if not line.strip().startswith(ignored)])
        if index:
            assert sum(line.strip() == "// [NOP]" for line in dump) == 1
    assert outputs[0] == outputs[1], "derived NOP fixture changed the tree"

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--dtc", required=True)
    parser.add_argument("--out", required=True)
    args = parser.parse_args()
    version = subprocess.run(
        [args.dtc, "--version"], check=True, capture_output=True, text=True
    ).stdout.strip()
    lines = [
        "/* Generated by gen_fixtures.py; do not edit. Source compiler: %s */" % version,
        "#ifndef PROBE_FIXTURES_H",
        "#define PROBE_FIXTURES_H",
        "#include <stdint.h>",
    ]
    with tempfile.TemporaryDirectory() as tmp:
        for name, source, options in FIXTURES:
            src = os.path.join(tmp, name + ".dts")
            dtb = os.path.join(tmp, name + ".dtb")
            with open(src, "w", encoding="ascii") as handle:
                handle.write(source)
            subprocess.run(
                [args.dtc, "-q", "-I", "dts", "-O", "dtb", *options, "-o", dtb, src],
                check=True,
            )
            with open(dtb, "rb") as handle:
                data = handle.read()
            emit(lines, name, data)
            if name == "fdt_model":
                nop = with_leading_nop(data)
                check_same_tree(args.dtc, tmp, data, nop)
                emit(lines, "fdt_leading_nop", nop)
    lines.append("#endif")
    with open(args.out, "w", encoding="ascii") as handle:
        handle.write("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
